export const CARDS_HAS_ERRORED = 'CARDS_HAS_ERRORED';
export const CARDS_IS_LOADING = 'CARDS_IS_LOADING';
export const CARDS_FETCH_DATA_SUCCESS = 'CARDS_FETCH_DATA_SUCCESS';
export const CARDS_CREATE = 'CARDS_CREATE';
export const CARDS_UPDATE = 'CARDS_UPDATE';
export const CARDS_DELETE = 'CARDS_DELETE';

export const COLUMNS_HAS_ERRORED = 'COLUMNS_HAS_ERRORED';
export const COLUMNS_IS_LOADING = 'COLUMNS_IS_LOADING';
export const COLUMNS_FETCH_DATA_SUCCESS = 'COLUMNS_FETCH_DATA_SUCCESS';
export const COLUMN_CREATE = 'COLUMN_CREATE';
export const COLUMN_UPDATE = 'COLUMN_UPDATE';
